version: '3.8'
services:
  identifier-app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    # Optionally (dev):
    # restart: unless-stopped 