version: '3.9'
services:
  identifier-app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    # Optionally (dev):
    restart: unless-stopped 